apiVersion: v1
kind: Service
metadata:
  name: devops-e2e-app
  labels:
    app: devops-e2e-app
spec:
  selector:
    app: devops-e2e-app
  ports:
    - name: http
      port: 80
      targetPort: 8080
  type: ClusterIP